// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urolmtklwgmrleaqwpic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyb2xtdGtsd2dtcmxlYXF3cGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDA3MTEsImV4cCI6MjA2MDU3NjcxMX0.gTVM4MbFheiipZ9GUWBaXANRAEvaRYLAOUQbYonRUPk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);